// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozejlakhelgspzlpqwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvemVqbGFraGVsZ3NwemxwcXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5NDYwNzUsImV4cCI6MjEwMDUyMjA3NX0.TqyV-ioHUBKyjyqmvhmFuPkbh2R203aA8Vd113lHl1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});